drop database webdev;
create database webdev;
use webdev;
CREATE USER 'bobbie'@'localhost' IDENTIFIED BY 'pug';
GRANT ALL PRIVILEGES ON USER.* TO 'bobbie'@'localhost';
GRANT ALL PRIVILEGES ON webdev.* TO 'bobbie'@'localhost';

create table USER(
USERID int(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Firstname VARCHAR(30) NOT NULL,
Lastname VARCHAR(30) NOT NULL,
Email VARCHAR(30) NOT NULL,
Address VARCHAR(70) NOT NULL,
Username VARCHAR(30) NOT NULL,
Password VARCHAR(30) NOT NULL
);

create table MOVIES(
MOVIEID int(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(20) NOT NULL,
Genre VARCHAR(15) NOT NULL,
Age VARCHAR(15) NOT NULL,
Runtime VARCHAR(15) NOT NULL,
Photo VARCHAR(45) NOT NULL,
Discription VARCHAR(400) NOT NULL
);

create table MOVIESWATCHED(
WATCHID int(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
USERID int(6) UNSIGNED NOT NULL,
MOVIEID int(6) UNSIGNED NOT NULL,
FOREIGN KEY (USERID) REFERENCES USER(USERID),
FOREIGN KEY (MOVIEID) REFERENCES MOVIES(MOVIEID)
);

create table SHOWTIMES(
DAYTYPE VARCHAR(1) NOT NULL,
MOVIEID int(6) UNSIGNED NOT NULL,
FOREIGN KEY (MOVIEID) REFERENCES MOVIES(MOVIEID),
TIME VARCHAR(5)
);
